version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    ports:
      - "${DB_EXTERNAL_PORT:-5433}:${DB_INTERNAL_PORT:-5432}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres_data:
