"""add access and refresh token in credentials

Revision ID: 8f23b25f49b9
Revises: 72463ef9456d
Create Date: 2025-04-14 13:20:08.052761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f23b25f49b9'
down_revision: Union[str, None] = '72463ef9456d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_credentials', sa.Column('access_token', sa.TEXT(), nullable=True))
    op.add_column('user_credentials', sa.Column('refresh_token', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_credentials', 'refresh_token')
    op.drop_column('user_credentials', 'access_token')
    # ### end Alembic commands ###
