/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as authSignupImport } from './routes/(auth)/sign_up'
import { Route as authLoginImport } from './routes/(auth)/login'
import { Route as appAppImport } from './routes/(app)/app'
import { Route as appAppStatisticsImport } from './routes/(app)/app.statistics'
import { Route as appAppRecommendationsImport } from './routes/(app)/app.recommendations'

// Create/Update Routes

const authSignupRoute = authSignupImport.update({
  id: '/(auth)/sign_up',
  path: '/sign_up',
  getParentRoute: () => rootRoute,
} as any)

const authLoginRoute = authLoginImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const appAppRoute = appAppImport.update({
  id: '/(app)/app',
  path: '/app',
  getParentRoute: () => rootRoute,
} as any)

const appAppStatisticsRoute = appAppStatisticsImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => appAppRoute,
} as any)

const appAppRecommendationsRoute = appAppRecommendationsImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => appAppRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)/app': {
      id: '/(app)/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof appAppImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign_up': {
      id: '/(auth)/sign_up'
      path: '/sign_up'
      fullPath: '/sign_up'
      preLoaderRoute: typeof authSignupImport
      parentRoute: typeof rootRoute
    }
    '/(app)/app/recommendations': {
      id: '/(app)/app/recommendations'
      path: '/recommendations'
      fullPath: '/app/recommendations'
      preLoaderRoute: typeof appAppRecommendationsImport
      parentRoute: typeof appAppImport
    }
    '/(app)/app/statistics': {
      id: '/(app)/app/statistics'
      path: '/statistics'
      fullPath: '/app/statistics'
      preLoaderRoute: typeof appAppStatisticsImport
      parentRoute: typeof appAppImport
    }
  }
}

// Create and export the route tree

interface appAppRouteChildren {
  appAppRecommendationsRoute: typeof appAppRecommendationsRoute
  appAppStatisticsRoute: typeof appAppStatisticsRoute
}

const appAppRouteChildren: appAppRouteChildren = {
  appAppRecommendationsRoute: appAppRecommendationsRoute,
  appAppStatisticsRoute: appAppStatisticsRoute,
}

const appAppRouteWithChildren =
  appAppRoute._addFileChildren(appAppRouteChildren)

export interface FileRoutesByFullPath {
  '/app': typeof appAppRouteWithChildren
  '/login': typeof authLoginRoute
  '/sign_up': typeof authSignupRoute
  '/app/recommendations': typeof appAppRecommendationsRoute
  '/app/statistics': typeof appAppStatisticsRoute
}

export interface FileRoutesByTo {
  '/app': typeof appAppRouteWithChildren
  '/login': typeof authLoginRoute
  '/sign_up': typeof authSignupRoute
  '/app/recommendations': typeof appAppRecommendationsRoute
  '/app/statistics': typeof appAppStatisticsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/(app)/app': typeof appAppRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/sign_up': typeof authSignupRoute
  '/(app)/app/recommendations': typeof appAppRecommendationsRoute
  '/(app)/app/statistics': typeof appAppStatisticsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/app'
    | '/login'
    | '/sign_up'
    | '/app/recommendations'
    | '/app/statistics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/app'
    | '/login'
    | '/sign_up'
    | '/app/recommendations'
    | '/app/statistics'
  id:
    | '__root__'
    | '/(app)/app'
    | '/(auth)/login'
    | '/(auth)/sign_up'
    | '/(app)/app/recommendations'
    | '/(app)/app/statistics'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  appAppRoute: typeof appAppRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
}

const rootRouteChildren: RootRouteChildren = {
  appAppRoute: appAppRouteWithChildren,
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/(app)/app",
        "/(auth)/login",
        "/(auth)/sign_up"
      ]
    },
    "/(app)/app": {
      "filePath": "(app)/app.tsx",
      "children": [
        "/(app)/app/recommendations",
        "/(app)/app/statistics"
      ]
    },
    "/(auth)/login": {
      "filePath": "(auth)/login.tsx"
    },
    "/(auth)/sign_up": {
      "filePath": "(auth)/sign_up.tsx"
    },
    "/(app)/app/recommendations": {
      "filePath": "(app)/app.recommendations.tsx",
      "parent": "/(app)/app"
    },
    "/(app)/app/statistics": {
      "filePath": "(app)/app.statistics.tsx",
      "parent": "/(app)/app"
    }
  }
}
ROUTE_MANIFEST_END */
